#lang racket/base
(require "language/base.rkt" "language/en.rkt")
(provide jgrammar)

(define jgrammar
  (make-grammar
   (list
    (irr-verb "be" '#("am" "is" "are") '#("was" "was" "were") "been")
    (regular-verb "do" "does" "did" "done")
    (regular-verb "have" "has" "had")
    (regular-verb "give" "gives" "gave" "given")
    (regular-verb "mean" "means" "meant")
    (regular-verb "study" "studies" "studied")
    (regular-verb "telephone" "telephones" "telephoned") ;; !!
    (regular-verb "plan" "plans" "planned")
    (regular-verb "organize" "organizes" "organized")
    (regular-verb "check" "checks" "checked")
    (regular-verb "inspect" "inspects" "inspected")
    (regular-verb "understand" "understands" "understood")
    (regular-verb "work" "works" "worked")
    (regular-verb "speak" "speaks" "spoke" "spoken")
    (regular-verb "eat" "eats" "ate" "eaten")
    (regular-verb "sleep" "sleeps" "slept")
    (regular-verb "stand" "stands" "stood")
    (regular-verb "say" "says" "said")
    (regular-verb "seek" "seeks" "sought")
    (regular-verb "live" "lives" "lived")
    (regular-verb "reside" "resides" "resided")
    (regular-verb "know" "knows" "knew" "known")
    (regular-verb "be able" "can" "can" "could") ;; !!!
    (regular-verb "walk" "walks" "walked")
    (regular-verb "go" "goes" "went" "gone")
    (regular-verb "think" "thinks" "thought")
    (regular-verb "invite" "invites" "invited")
    (regular-verb "read" "reads" "read")
    (regular-verb "drink" "drinks" "drank" "drunk")
    (regular-verb "want" "wants" "wanted")
    (regular-verb "help" "helps" "helped")
    (regular-verb "teach" "teaches" "taught")
    (regular-verb "learn" "learns" "learned")
    (regular-verb "start" "starts" "started")
    (regular-verb "begin" "begins" "began" "begun")
    (regular-verb "end" "ends" "ended")
    (regular-verb "shop" "shops" "shopped")
    (regular-verb "cook" "cooks" "cooked")
    (regular-verb "clean" "cleans" "cleaned")
    (regular-verb "get up" "gets up" "got up")
    (regular-verb "dine" "dines" "dined")
    (regular-verb "dance" "dances" "danced")
    (regular-verb "eat breakfast" "eats breakfast" "ate breakfast" "eaten breakfast")
    (regular-verb "listen" "listens" "listened")
    (regular-verb "eat lunch" "eats lunch" "ate lunch")
    (regular-verb "exercise" "exercises" "exercised")
    (regular-verb "swim" "swims" "swam" "swum")
    (regular-verb "play" "plays" "played")
    (regular-verb "write" "writes" "wrote" "written")
    (regular-verb "forget" "forgets" "forgot" "forgotten"))))
